export const AGREGAR_TOKEN = 'AGREGAR_TOKEN';
export const TOKEN_ERROR = 'TOKEN_ERROR';
export const TOKEN_EXITO = 'TOKEN_EXITO';

export const COMENZAR_DESCARGA_PRODUCTOS = 'COMENZAR_DESCARGA_PRODUCTOS';
export const DESCARGA_PRODUCTOS_EXITO = 'DESCARGA_PRODUCTOS_EXITO';
export const DESCARGA_PRODUCTOS_ERROR = 'DESCARGA_PRODUCTOS_ERROR';


export const COMENZAR_GUARDAR_PRODUCTO = 'COMENZAR_GUARDAR_PRODUCTO';
export const GUARDAR_PRODUCTO_EXITO = 'GUARDAR_PRODUCTO_EXITO';
export const GUARDAR_PRODUCTO_ERROR = 'GUARDAR_PRODUCTO_ERROR';

export const COMENZAR_GUARDAR_CARRITO = 'COMENZAR_GUARDAR_CARRITO';
export const GUARDAR_CARRITO_EXITO = 'GUARDAR_CARRITO_EXITO';
export const GUARDAR_CARRITO_ERROR = 'GUARDAR_CARRITO_ERROR';

export const COMENZAR_GUARDAR_USUARIO = 'COMENZAR_GUARDAR_USUARIO';
export const GUARDAR_USUARIO_EXITO = 'GUARDAR_USUARIO_EXITO';
export const GUARDAR_USUARIO_ERROR = 'GUARDAR_USUARIO_ERROR';