export const AGREGAR_TOKEN = 'AGREGAR_TOKEN';
export const TOKEN_ERROR = 'TOKEN_ERROR';
export const TOKEN_EXITO = 'TOKEN_EXITO';

export const COMENZAR_DESCARGA_PRODUCTOS = 'COMENZAR_DESCARGA_PRODUCTOS';
export const DESCARGA_PRODUCTOS_EXITO = 'DESCARGA_PRODUCTOS_EXITO';
export const DESCARGA_PRODUCTOS_ERROR = 'DESCARGA_PRODUCTOS_ERROR';


export const COMENZAR_GUARDAR_PRODUCTO = 'COMENZAR_GUARDAR_PRODUCTO';
export const GUARDAR_PRODUCTO_EXITO = 'GUARDAR_PRODUCTO_EXITO';
export const GUARDAR_PRODUCTO_ERROR = 'GUARDAR_PRODUCTO_ERROR';

export const COMENZAR_GUARDAR_CARRITO = 'COMENZAR_GUARDAR_CARRITO';
export const GUARDAR_CARRITO_EXITO = 'GUARDAR_CARRITO_EXITO';
export const GUARDAR_CARRITO_ERROR = 'GUARDAR_CARRITO_ERROR';

export const COMENZAR_GUARDAR_USUARIO = 'COMENZAR_GUARDAR_USUARIO';
export const GUARDAR_USUARIO_EXITO = 'GUARDAR_USUARIO_EXITO';
export const GUARDAR_USUARIO_ERROR = 'GUARDAR_USUARIO_ERROR';

export const COMENZAR_GUARDAR_INDEX = 'COMENZAR_GUARDAR_INDEX';
export const GUARDAR_INDEX_EXITO = 'GUARDAR_INDEX_EXITO';
export const GUARDAR_INDEX_ERROR = 'GUARDAR_INDEX_ERROR';

export const COMENZAR_GUARDAR_BOOLEAN = 'COMENZAR_GUARDAR_BOOLEAN';
export const GUARDAR_BOOLEAN_EXITO = 'GUARDAR_BOOLEAN_EXITO';
export const GUARDAR_BOOLEAN_ERROR = 'GUARDAR_BOOLEAN_ERROR';

export const COMENZAR_GUARDAR_BEBIDAS = 'COMENZAR_GUARDAR_BEBIDAS';
export const GUARDAR_BEBIDAS_EXITO = 'GUARDAR_BEBIDAS_EXITO';
export const GUARDAR_BEBIDAS_ERROR = 'GUARDAR_BEBIDAS_ERROR';

export const COMENZAR_GUARDAR_DRINKS = 'COMENZAR_GUARDAR_DRINKS';
export const GUARDAR_DRINKS_EXITO = 'GUARDAR_DRINKS_EXITO';
export const GUARDAR_DRINKS_ERROR = 'GUARDAR_DRINKS_ERROR';

export const COMENZAR_GUARDAR_TYPE = 'COMENZAR_GUARDAR_TYPE';
export const GUARDAR_TYPE_EXITO = 'GUARDAR_TYPE_EXITO';
export const GUARDAR_TYPE_ERROR = 'GUARDAR_TYPE_ERROR';

export const COMENZAR_GUARDAR_PAYMENT = 'COMENZAR_GUARDAR_PAYMENT';
export const GUARDAR_PAYMENT_EXITO = 'GUARDAR_PAYMENT_EXITO';
export const GUARDAR_PAYMENT_ERROR = 'GUARDAR_PAYMENT_ERROR';

export const COMENZAR_GUARDAR_ORDENES = 'COMENZAR_GUARDAR_ORDENES';
export const GUARDAR_ORDENES_EXITO = 'GUARDAR_ORDENES_EXITO';
export const GUARDAR_ORDENES_ERROR = 'GUARDAR_ORDENES_ERROR';